### ISSUE TITLE
Addition of Level 0: Basic Tutorial Regarding Towers

### ISSUE THREAD

**Issue by Blazeur22** [FixAkaTheFix/Tower-Pixel-Dungeon#1]
I am confused on how to upgrade the towers.
I tried several ways like putting upgrade scroll with tower kits in alchemy and by throwing the scroll at already-functioning towers.

I don't know if it's bugged, I'm lacking an item to upgrade them or doing it wrong. It is kinda crucial because levels from 2 and above are really difficult, my Level 1 towers are getting cooked by crabs' dps and snakes' evasion.

**Comment by fadedwater** [comment]
You can use magic towers to solve snakes and use walls to block crabs.
Towers can be upgraded in deeper depths using money.
