### ISSUE TITLE
Healing Items & Potions Supposed To Fix Barricades Not Working

### ISSUE THREAD

**Issue by Blazeur22** [FixAkaTheFix/Tower-Pixel-Dungeon#2]
+++++++++++++++++
Healing Potion
Honey Elixir Potion
Rejuvenation Potion
Time-Bomb of Growth
==================

I don't know if it's also supposed to fix the other towers and amulet as well. But it doesn't work in any way I use it on them.

**Comment by FixAkaTheFix** [comment]
Healing pot's don't work on others in original shpd even.
If you speak about the amulet, the amulet can't be healed by most means, by all means even. The only way to directly protect it is to use the transfusion wand on it, which gives it 5 shield.
