### ISSUE TITLE
Readjusment of Preparation Time and Gold Gain In Each Wave

### ISSUE THREAD

**Issue by Blazeur22** [FixAkaTheFix/Tower-Pixel-Dungeon#3]
Having a hard time gathering loot around the map and buying/preparing defenses because the amount of steps and gold gain after each wave is lesser than I imagined.

Resulting in a disadvantage against a wave of special enemies (throwing gnolls, snakes, crabs, black rodent, etc).

**Comment by FixAkaTheFix** [comment]
Being done currently, sorry for not responding. The game does need balancing, true.
