### ISSUE TITLE
Projecting Goo attempts to pump up even if it makes no sense

### ISSUE THREAD

**Issue by haltalt** [FixAkaTheFix/Tower-Pixel-Dungeon#9]
In hard mode, the Goo can be a giant or projecting champion. The Goo's attack logic attempts to pump up even if the enemy is too far away - the code does not account for possible range increase. As a result, it starts pumping it and then it immediately stops, wasting one turn.
Suggested fix: change https://github.com/FixAkaTheFix/Tower-Pixel-Dungeon/blob/03dbe0ca70cdb2684de5d2e965a4a0c8f0afa49f/pixel-towers-master/core/src/main/java/com/towerpixel/towerpixeldungeon/actors/mobs/Goo.java#L166
to be
`} else if (Dungeon.level.distance(enemy.pos, pos) > 1 || pumpedUp >= 2 || Random.Int( (HP*2 <= HT) ? 2 : 5 ) > 0) {`
If you want goo to still attempt to pump up when it is two tiles away from an enemy, then that is also an option.

**Comment by FixAkaTheFix** [comment]
Is fixed, will be changed in newer versions. Thank you for reporting!
